trigger: none

pool:
  name: "Win"
  demands:
    - Agent.Name -equals win

variables:
  - group: Terraform

steps:
- task: PowerShell@2
  displayName: "Tworzenie terraform.tfvars.json z wartości zmiennych"
  inputs:
    targetType: 'inline'
    script: |
      $clientId = "$(ARM_CLIENT_ID)"
      $clientSecret = "$(ARM_CLIENT_SECRET)"
      $tenantId = "$(ARM_TENANT_ID)"
      $subscriptionId = "$(ARM_SUBSCRIPTION_ID)"

      $lines = @()
      $lines += '{'
      $lines += '  "client_id": "' + $clientId + '",'
      $lines += '  "client_secret": "' + $clientSecret + '",'
      $lines += '  "tenant_id": "' + $tenantId + '",'
      $lines += '  "subscription_id": "' + $subscriptionId + '"'
      $lines += '}'

      $lines | Out-File -FilePath terraform.tfvars.json -Encoding utf8

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'terraform.tfvars.json'
    artifact: 'tfvars'
  displayName: "Publikuj artifact tfvars"
