trigger: none

name: 'tfvars-generate'
pool:
  name: "Win"
  demands:
    - Agent.Name -equals win

steps:
- script: |
    echo "${{ parameters.tfvarsContent }}" > terraform.tfvars.json
  displayName: "Stwórz terraform.tfvars.json z przekazanej zmiennej"
- script: |
    echo "Zmienna TFVARS_CONTENT:"
    echo "$TFVARS_CONTENT"
  displayName: "Debug TFVARS_CONTENT"


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'terraform.tfvars.json'
    artifactName: 'tfvars'
