trigger: none

name: 'tfvars-generate'

pool:
  name: "Win"
  demands:
    - Agent.Name -equals win

steps:
- task: PowerShell@2
  displayName: "Zapisz terraform.tfvars.json"
  inputs:
    targetType: inline
    script: |
      $env:TFVARS_CONTENT | Set-Content -Path terraform.tfvars.json -Encoding UTF8
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'terraform.tfvars.json'
    artifactName: 'tfvars'
