trigger: none

pool:
  name: "Win"
  demands:
    - Agent.Name -equals win

variables:
  - group: Terraform

steps:
- task: PowerShell@2
  displayName: "Uzupełnij terraform.tfvars.json o dane uwierzytelniające"
  inputs:
    targetType: 'inline'
    script: |
      $jsonPath = "terraform.tfvars.json"
      $json = Get-Content $jsonPath | ConvertFrom-Json

      $json.client_id = "$(ARM_CLIENT_ID)"
      $json.client_secret = "$(ARM_CLIENT_SECRET)"
      $json.tenant_id = "$(ARM_TENANT_ID)"
      $json.subscription_id = "$(ARM_SUBSCRIPTION_ID)"

      $json | ConvertTo-Json -Depth 3 | Out-File $jsonPath -Encoding utf8

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'terraform.tfvars.json'
    artifact: 'tfvars'
  displayName: "Publikuj tfvars"
