trigger: none

name: 'tfvars-generate'

pool:
  name: "Win"
  demands:
    - Agent.Name -equals win

steps:
- task: PowerShell@2
  displayName: "Zapisz terraform.tfvars.json bez BOM"
  inputs:
    targetType: inline
    script: |
      $utf8NoBOM = New-Object System.Text.UTF8Encoding($false)
      [System.IO.File]::WriteAllText("terraform.tfvars.json", $env:TFVARS_CONTENT, $utf8NoBOM)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'terraform.tfvars.json'
    artifactName: 'tfvars'
